export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = " USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = " USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const SHOP_DETAILS_REQUEST = "SHOP_DETAILS_REQUEST";
export const SHOP_DETAILS_SUCCESS = "SHOP_DETAILS_SUCCESS";
export const SHOP_DETAILS_FAIL = "SHOP_DETAILS_FAIL";
export const SHOP_DETAILS_RESET = "SHOP_DETAILS_RESET";


export const SHOP_LIST_REQUEST = "SHOP_LIST_REQUEST";
export const SHOP_LIST_SUCCESS = " SHOP_LIST_SUCCESS";
export const SHOP_LIST_FAIL = "SHOP_LIST_FAIL";
export const SHOP_LIST_RESET = "SHOP_LIST_RESET";

export const SHOP_DELETE_REQUEST = "SHOP_DELETE_REQUEST";
export const SHOP_DELETE_SUCCESS = "SHOP_DELETE_SUCCESS";
export const SHOP_DELETE_FAIL = "SHOP_DELETE_FAIL";

